version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    working_directory: ~/nautilus-folder-icons
    steps:
      - run: >
          dnf -y install
          gettext
          appstream
          libappstream-glib
          gobject-introspection-devel
          gtk3-devel
          meson
          ninja-build
          python3-pip
          python3-gobject
      - checkout
      - run: pip3 install pycodestyle
      - run: meson builddir
      - run: ninja -C builddir test
      - run: ninja -C builddir install
